### PR TITLE
Fix minimist vulnerability

### PR DESCRIPTION
**Pull request by crism**
This fixes issue #12 and some other things found by `npm audit`.

### CODE REVIEW

**Comment by crism** [comment]
This was inappropriately against `master` instead of `development`.

**Comment by crism** [comment]
Reopening per suggestion from owners.

**Comment by BillFarber** [comment]
This PR is limited to updates to the dependency versions. Looks good to me.

**Comment by BillFarber** [comment]
I noticed in the PR for grove-cli, the version property in package-lock.json was bumped.
Should it be bumped here?

**Comment by grtjn** [comment]
Version in package-lock is normally kept in sync with package.json automatically by npm. Since there is no package.json in this PR, I suspect should have been added as well.

I ran some more elaborate npm updates and npm audits on dev branch though, and pushed them into dev, and merged that into master. All audit messages should be gone now. This PR should be redundant..

**Comment by crism** [comment]
Thanks, @grtjn! I will withdraw this one, then.

**Pull request closed without merging**
